Remove the MPT-internal dev tools upon project initialization

diff --git a/init_project_from_template b/init_project_from_template
--- a/init_project_from_template
+++ b/init_project_from_template
@@ -8,9 +8,27 @@
 #
 # This works on Mac and Linux. If you're running Windows, install Ubuntu for Windows and use that!
 
+# Options:
+#   -d, --dev  - Backdoor for MPT devs: leave in special MPT targets
+
 # Don't change this file!
 
 set -e
+
+DO_DEV=n
+while [[ $# -gt 0 ]]; do
+  arg="$1"
+  shift
+  case $arg in
+    -d|--dev)
+      $DO_DEV=y
+      ;;
+    *)
+      echo >&2 "Error: unknown option: $arg"
+      exit 1
+      ;;
+  esac
+done
 
 source ./project_settings.sh
 
@@ -108,6 +126,11 @@ perl -spi -e "s/command: .\/MatlabProjectTemplate\/test_project_initialization/c
   ./.circleci/config.yml
 perl -spi -e "s/- .\/MatlabProjectTemplate\/test_project_initialization//" \
   .travis.yml
+
+if [[ "$DO_DEV" != "y" ]]; then
+  # Remove special MPT-dev tools
+  perl -0pi -e 's/# start-template-internal.*# end-template-internal//smg' Makefile
+fi
 
 rm -rf docs doc/*
 cp -R doc-src-$DOCSITETOOL docs
