Notes on detecting changes

diff --git a/dev-kit/make_release b/dev-kit/make_release
--- a/dev-kit/make_release
+++ b/dev-kit/make_release
@@ -28,11 +28,15 @@ if [[ ! -z "$(git status --porcelain)" ]]; then
   echo >&2 "Error: Your repo is not clean! There are local changes. No release for you!"
   exit 1
 fi
-must git remote update
-if [[ ! -z "$(git status -uno)" ]]; then
-  echo >&2 "Error: There are pending remote changes in git. No release for you!"
-  exit 1
-fi
+
+# TODO: Figure out how to check for pending remote changes on the tracked branch
+# in git. Diffing origin/main is incorrect, because we may be releasing a patch
+# release from a different branch.
+#must git remote update
+#if [[ ! -z "$(git diff origin/main)" ]]; then
+#  echo >&2 "Error: There are pending remote changes in git. No release for you!"
+#  exit 1
+#fi
 
 # First run the tests before we make any changes
 
